version: '3.8'

services:
  travelpacker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: travelpacker
    restart: unless-stopped
    ports:
      - "8123:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - SCRIPT_NAME=/travelpacker # CHANGE IT
      - SECRET_KEY=secret_key # CHANGE IT 
      
