from app import app, db, Category, Item

MASSIVE_SEED_DATA = {
    ("Essentials", "Esenciales"): [
        ("Passport", "Pasaporte"),
        ("ID / Driver's License", "DNI / Carnet de Conducir"),
        ("Credit Cards", "Tarjetas de Crédito"),
        ("Cash", "Dinero en efectivo"),
        ("House Keys", "Llaves de casa"),
        ("Travel Tickets", "Billetes de viaje"),
        ("Itinerary / Reservations", "Itinerario / Reservas"),
        ("Health Insurance Card", "Tarjeta Sanitaria"),
        ("Travel Insurance Documents", "Documentos de seguro de viaje"),
        ("Visa (if required)", "Visado (si es necesario)"),
        ("Emergency Contacts", "Contactos de emergencia"),
        ("Copies of Documents", "Copias de documentos"),
        ("Wallet", "Cartera"),
        ("Phone", "Teléfono móvil"),
        ("Laptop / Tablet", "Portátil / Tablet"),
        ("Chargers", "Cargadores"),
        ("Power Bank", "Batería externa"),
        ("Headphones", "Auriculares"),
        ("Pen & Notebook", "Bolígrafo y libreta"),
        ("Water Bottle", "Botella de agua"),
    ],
    ("Electronics", "Electrónica"): [
        ("Phone", "Teléfono móvil"),
        ("Phone Charger", "Cargador de móvil"),
        ("Power Bank", "Batería externa"),
        ("Plug Adapter", "Adaptador de corriente"),
        ("Headphones", "Auriculares"),
        ("Laptop", "Portátil"),
        ("Laptop Charger", "Cargador del portátil"),
        ("Camera & SD Card", "Cámara y Tarjeta SD"),
        ("E-reader (Kindle)", "E-reader / Libro electrónico"),
        ("Smartwatch", "Reloj inteligente"),
        ("Smartwatch Charger", "Cargador de reloj inteligente"),
        ("USB Cables", "Cables USB"),
        ("Portable Hard Drive", "Disco duro portátil"),
        ("Bluetooth Speaker", "Altavoz Bluetooth"),
        ("Action Camera", "Cámara de acción"),
        ("Drone", "Dron"),
        ("Drone Accessories", "Accesorios del dron"),
        ("Tripod", "Trípode"),
        ("Camera Battery", "Batería de cámara"),
        ("Memory Card Reader", "Lector de tarjetas de memoria"),
        ("Extension Cord", "Cable alargador"),
        ("Multi-USB Charger", "Cargador multi-USB"),
        ("Wireless Charger", "Cargador inalámbrico"),
        ("Tablet", "Tablet"),
        ("Mouse", "Ratón"),
        ("Keyboard", "Teclado"),
        ("HDMI Cable", "Cable HDMI"),
    ],
    ("Toiletries", "Aseo Personal"): [
        ("Toothbrush", "Cepillo de dientes"),
        ("Toothpaste", "Pasta de dientes"),
        ("Dental Floss", "Hilo dental"),
        ("Mouthwash", "Enjuague bucal"),
        ("Deodorant", "Desodorante"),
        ("Shower Gel", "Gel de ducha"),
        ("Shampoo", "Champú"),
        ("Hair Conditioner", "Acondicionador"),
        ("Hairbrush / Comb", "Cepillo / Peine"),
        ("Hair Styling Products", "Productos para peinar"),
        ("Razor / Shaving Kit", "Maquinilla / Kit de afeitar"),
        ("Shaving Cream", "Crema de afeitar"),
        ("Aftershave", "Loción post-afeitado"),
        ("Nail Clippers", "Cortaúñas"),
        ("Tweezers", "Pinzas de depilar"),
        ("Scissors", "Tijeras pequeñas"),
        ("Moisturizer", "Crema hidratante"),
        ("Face Wash", "Limpiador facial"),
        ("Face Toner", "Tónico facial"),
        ("Sunscreen (Face)", "Protector solar facial"),
        ("Lip Balm", "Bálsamo labial"),
        ("Perfume / Cologne", "Perfume / Colonia"),
        ("Makeup", "Maquillaje"),
        ("Makeup Remover", "Desmaquillante"),
        ("Cotton Pads", "Discos de algodón"),
        ("Feminine Hygiene Products", "Productos de higiene íntima"),
        ("Hand Sanitizer", "Desinfectante de manos"),
        ("Body Lotion", "Loción corporal"),
        ("Hair Ties / Clips", "Gomas / Pinzas de pelo"),
        ("Dry Shampoo", "Champú en seco"),
        ("Body Scrub", "Exfoliante corporal"),
        ("Face Mask", "Mascarilla facial"),
        ("Eye Cream", "Crema para ojos"),
        ("Serum", "Sérum facial"),
        ("Beard Oil", "Aceite para barba"),
        ("Beard Trimmer", "Recortador de barba"),
        ("Travel Mirror", "Espejo de viaje"),
        ("Toiletry Bag", "Neceser"),
        ("Q-tips", "Bastoncillos de algodón"),
        ("Tissues", "Pañuelos de papel"),
    ],
    ("Clothing (General)", "Ropa (General)"): [
        ("Underwear", "Ropa interior"),
        ("Socks", "Calcetines"),
        ("T-shirts", "Camisetas"),
        ("Polo Shirts", "Camisetas polo"),
        ("Pants / Jeans", "Pantalones / Vaqueros"),
        ("Shorts", "Pantalones cortos"),
        ("Sweaters / Hoodies", "Jerséis / Sudaderas"),
        ("Cardigan", "Cárdigan"),
        ("Pajamas", "Pijama"),
        ("Everyday Shoes", "Zapatillas de uso diario"),
        ("Dress Shoes", "Zapatos de vestir"),
        ("Flip Flops", "Chanclas"),
        ("Jacket", "Chaqueta / Cazadora"),
        ("Rain Jacket", "Chaqueta impermeable"),
        ("Belt", "Cinturón"),
        ("Dress / Skirt", "Vestido / Falda"),
        ("Blazer / Suit Jacket", "Chaqueta de traje"),
        ("Tie", "Corbata"),
        ("Formal Shirt", "Camisa formal"),
        ("Casual Shirt", "Camisa casual"),
        ("Tank Tops", "Camisetas sin mangas"),
        ("Leggings", "Mallas"),
        ("Yoga Pants", "Pantalones de yoga"),
        ("Tracksuit", "Chándal"),
        ("Hat / Cap", "Sombrero / Gorra"),
        ("Sunglasses", "Gafas de sol"),
        ("Gloves", "Guantes"),
        ("Scarf", "Bufanda"),
        ("Swimsuit", "Bañador"),
        ("Beach Cover-up", "Pareo / Cubre bañador"),
        ("Sleepwear", "Ropa de dormir"),
        ("Lingerie", "Lencería"),
        ("Sports Bra", "Sujetador deportivo"),
        ("Compression Socks", "Calcetines de compresión"),
        ("Work Uniform", "Uniforme de trabajo"),
        ("Safety Vest", "Chaleco de seguridad"),
        ("Apron", "Delantal"),
        ("Robe", "Albornoz"),
        ("Slippers", "Zapatillas de casa"),
        ("Boots", "Botas"),
    ],
    ("Winter", "Invierno"): [
        ("Heavy Coat", "Abrigo grueso"),
        ("Down Jacket", "Chaqueta de plumas"),
        ("Scarf", "Bufanda"),
        ("Gloves", "Guantes"),
        ("Mittens", "Manoplas"),
        ("Beanie / Winter Hat", "Gorro de invierno"),
        ("Earmuffs", "Orejeras"),
        ("Thermal Underwear", "Ropa interior térmica"),
        ("Thermal Socks", "Calcetines térmicos"),
        ("Winter Boots", "Botas de invierno"),
        ("Snow Boots", "Botas de nieve"),
        ("Wool Socks", "Calcetines de lana"),
        ("Fleece Jacket", "Chaqueta de forro polar"),
        ("Sweater", "Jersey de lana"),
        ("Turtleneck", "Jersey de cuello alto"),
        ("Vest", "Chaleco"),
        ("Hand Warmers", "Calientamanos"),
        ("Lip Ointment", "Pomada para labios cortados"),
        ("Face Moisturizer", "Hidratante facial"),
        ("Sunscreen (Winter)", "Protector solar (invierno)"),
        ("Ski Goggles", "Gafas de esquí"),
        ("Neck Warmer", "Calentador de cuello"),
        ("Snow Pants", "Pantalones de nieve"),
        ("Waterproof Gloves", "Guantes impermeables"),
        ("Ice Grippers", "Crampones para hielo"),
    ],
    ("Summer & Beach", "Verano y Playa"): [
        ("Swimsuit", "Bañador"),
        ("Rash Guard", "Camiseta de protección solar"),
        ("Sunscreen", "Protector solar"),
        ("Sunglasses", "Gafas de sol"),
        ("Beach Towel", "Toalla de playa"),
        ("Flip Flops", "Chanclas"),
        ("Sun Hat / Cap", "Sombrero / Gorra"),
        ("Beach Bag", "Bolsa de playa"),
        ("Aftersun", "Aftersun / Crema post-solar"),
        ("Snorkel Gear", "Gafas de buceo / Snorkel"),
        ("Snorkel Fins", "Aletas de buceo"),
        ("Beach Umbrella", "Sombrilla de playa"),
        ("Beach Chair", "Silla de playa"),
        ("Beach Blanket", "Manta de playa"),
        ("Beach Toys", "Juguetes de playa"),
        ("Sandals", "Sandalias"),
        ("Beach Cover-up", "Pareo / Cubre bañador"),
        ("Waterproof Phone Case", "Funda impermeable para móvil"),
        ("Dry Bag", "Bolsa estanca"),
        ("Beach Games", "Juegos de playa"),
        ("Beach Volleyball", "Balón de vóley playa"),
        ("Frisbee", "Frisbee"),
        ("Cooler Bag", "Nevera portátil"),
        ("Ice Packs", "Bolsas de hielo"),
        ("Beach Snacks", "Snacks para la playa"),
        ("Lip Balm with SPF", "Bálsamo labial con SPF"),
        ("Hair Ties", "Gomas de pelo"),
        ("Hair Clip", "Pinza de pelo"),
        ("Book", "Libro"),
        ("Mosquito Repellent", "Repelente de mosquitos"),
    ],
    ("Health & First Aid", "Salud y Botiquín"): [
        ("Plasters", "Tiritas"),
        ("Painkillers", "Analgésicos (Paracetamol/Ibuprofeno)"),
        ("Personal Prescriptions", "Medicación personal"),
        ("Mosquito Repellent", "Repelente de mosquitos"),
        ("Mosquito Repellent Wristbands", "Pulseras antimosquitos"),
        ("Thermometer", "Termómetro"),
        ("Antihistamines", "Antihistamínicos"),
        ("Motion Sickness Pills", "Pastillas para el mareo"),
        ("Hand Sanitizer", "Desinfectante de manos"),
        ("Tissues", "Pañuelos de papel"),
        ("Antiseptic Wipes", "Toallitas antisépticas"),
        ("Gauze Pads", "Gasas estériles"),
        ("Medical Tape", "Esparadrapo"),
        ("Bandages", "Vendas"),
        ("Scissors", "Tijeras"),
        ("Tweezers", "Pinzas"),
        ("Safety Pins", "Imperdibles"),
        ("Antibiotic Ointment", "Pomada antibiótica"),
        ("Hydrocortisone Cream", "Crema de hidrocortisona"),
        ("Antacid", "Antiácido"),
        ("Diarrhea Medicine", "Medicina para la diarrea"),
        ("Constipation Medicine", "Medicina para el estreñimiento"),
        ("Eye Drops", "Gotas para los ojos"),
        ("Ear Plugs", "Tapones para los oídos"),
        ("Sleep Mask", "Antifaz para dormir"),
        ("Inhaler", "Inhalador"),
        ("Glucose Tablets", "Tabletas de glucosa"),
        ("Allergy Medication", "Medicación para alergias"),
        ("Burn Cream", "Crema para quemaduras"),
        ("Insect Bite Relief", "Alivio para picaduras de insectos"),
        ("First Aid Kit", "Botiquín de primeros auxilios"),
        ("Emergency Contact Card", "Tarjeta de contacto de emergencia"),
        ("Medical History Card", "Tarjeta de historial médico"),
        ("Vitamins", "Vitaminas"),
        ("Supplements", "Suplementos"),
        ("Protein Bars", "Barritas de proteínas"),
        ("Electrolyte Powder", "Polvo de electrolitos"),
        ("Water Purification Tablets", "Tabletas purificadoras de agua"),
        ("Face Masks", "Mascarillas"),
    ],
    ("Pets", "Animales domésticos"): [
        ("Pet Food", "Comida para mascotas"),
        ("Food Bowl", "Comedero"),
        ("Water Bowl", "Bebedero"),
        ("Leash", "Correa"),
        ("Long Leash", "Correa larga"),
        ("Collar / Harness", "Collar / Arnés"),
        ("Poop Bags", "Bolsas para excrementos"),
        ("Carrier", "Transportín"),
        ("Health Card", "Cartilla sanitaria"),
        ("Passport", "Pasaporte"),
        ("Muzzle", "Bozal"),
        ("Pet Bed", "Cama de la mascota"),
        ("Pet Blanket", "Manta de la mascota"),
        ("Favorite Toys", "Juguetes favoritos"),
        ("Chew Toys", "Juguetes para morder"),
        ("Pet Towel", "Toalla para mascotas"),
        ("Pet Shampoo", "Champú para mascotas"),
        ("Brush / Comb", "Cepillo / Peine"),
        ("Flea & Tick Treatment", "Tratamiento antipulgas y garrapatas"),
        ("Pet Wipes", "Toallitas para mascotas"),
        ("Pet Treats", "Premios para mascotas"),
        ("Pet Medication", "Medicación para mascotas"),
        ("Pet First Aid Kit", "Botiquín para mascotas"),
        ("Pet Life Jacket", "Chaleco salvavidas para mascotas"),
        ("Pet Seat Belt", "Cinturón de seguridad para mascotas"),
        ("Pet Car Barrier", "Barrera para coche de mascotas"),
        ("Pet Tags", "Placas de identificación"),
        ("Pet Whistle", "Silbato"),
        ("Training Treats", "Premios de entrenamiento"),
        ("Pet Training Clicker", "Clicker de entrenamiento"),
        ("Pet Nail Clippers", "Cortaúñas para mascotas"),
        ("Pet Toothbrush", "Cepillo de dientes para mascotas"),
    ],
    ("Baby & Toddler", "Bebé y Niño Pequeño"): [
        ("Diapers", "Pañales"),
        ("Baby Wipes", "Toallitas húmedas"),
        ("Pacifier", "Chupete"),
        ("Baby Food / Formula", "Comida / Leche de fórmula"),
        ("Bottles", "Biberones"),
        ("Bottle Brush", "Cepillo para biberones"),
        ("Stroller", "Cochecito / Carrito"),
        ("Stroller Rain Cover", "Cubierta de lluvia para cochecito"),
        ("Baby Clothes", "Ropa de bebé"),
        ("Baby Shoes", "Zapatos de bebé"),
        ("Baby Socks", "Calcetines de bebé"),
        ("Baby Hats", "Gorritos de bebé"),
        ("Bibs", "Baberos"),
        ("Changing Pad", "Cambiador portátil"),
        ("Diaper Cream", "Crema para pañales"),
        ("Baby Monitor", "Vigilabebés"),
        ("Baby Blanket", "Manta de bebé"),
        ("Baby Carrier", "Portabebés"),
        ("Baby Car Seat", "Silla de coche para bebé"),
        ("Baby Bath Tub", "Bañera para bebé"),
        ("Baby Shampoo", "Champú para bebé"),
        ("Baby Lotion", "Loción para bebé"),
        ("Baby Sunscreen", "Protector solar para bebé"),
        ("Baby Thermometer", "Termómetro para bebé"),
        ("Baby Medicine", "Medicina para bebé"),
        ("Baby First Aid Kit", "Botiquín para bebé"),
        ("Baby Toys", "Juguetes para bebé"),
        ("Baby Books", "Libros para bebé"),
        ("Baby Snacks", "Snacks para bebé"),
        ("Baby Utensils", "Cubiertos para bebé"),
        ("Baby Plate", "Plato para bebé"),
        ("Baby Cup", "Vaso para bebé"),
        ("Baby High Chair", "Trona para bebé"),
        ("Baby Gate", "Barrera para bebé"),
        ("Baby Proofing Kit", "Kit de seguridad para bebé"),
        ("Baby Nail Clippers", "Cortaúñas para bebé"),
        ("Baby Toothbrush", "Cepillo de dientes para bebé"),
        ("Baby Hairbrush", "Cepillo de pelo para bebé"),
        ("Baby Sleep Sack", "Saco de dormir para bebé"),
        ("Baby Night Light", "Luz nocturna para bebé"),
    ],
    ("Work & Business", "Trabajo y Negocios"): [
        ("Notebook", "Cuaderno / Libreta"),
        ("Pens", "Bolígrafos"),
        ("Highlighters", "Rotuladores fluorescentes"),
        ("Business Cards", "Tarjetas de visita"),
        ("Work ID / Badge", "Acreditación / Pase de empresa"),
        ("USB Drive", "Memoria USB / Pendrive"),
        ("Laptop", "Portátil"),
        ("Laptop Charger", "Cargador de portátil"),
        ("Mouse", "Ratón"),
        ("Mouse Pad", "Alfombrilla de ratón"),
        ("Headset", "Auriculares con micrófono"),
        ("Webcam", "Cámara web"),
        ("Portable Monitor", "Monitor portátil"),
        ("HDMI Cable", "Cable HDMI"),
        ("Power Strip", "Regleta de enchufes"),
        ("Extension Cord", "Cable alargador"),
        ("Paper Clips", "Clips"),
        ("Scissors", "Tijeras"),
        ("Tape", "Cinta adhesiva"),
        ("Glue Stick", "Pegamento en barra"),
        ("Calculator", "Calculadora"),
        ("Planner", "Planificador"),
        ("Calendar", "Calendario"),
        ("Sticky Notes", "Notas adhesivas"),
        ("File Folders", "Carpetas de archivos"),
        ("Whiteboard Markers", "Rotuladores de pizarra"),
        ("Eraser", "Borrador"),
        ("Ruler", "Regla"),
    ],
    ("Camping", "Acampada"): [
        ("Tent", "Tienda de campaña"),
        ("Tent Footprint", "Lona para tienda"),
        ("Tent Stakes", "Estacas de tienda"),
        ("Sleeping Bag", "Saco de dormir"),
        ("Sleeping Pad", "Colchoneta de dormir"),
        ("Camping Pillow", "Almohada de camping"),
        ("Flashlight / Headlamp", "Linterna / Frontal"),
        ("Extra Batteries", "Pilas de repuesto"),
        ("Pocket Knife", "Navaja multiusos"),
        ("Multi-tool", "Herramienta multiusos"),
        ("Matches / Lighter", "Cerillas / Mechero"),
        ("Fire Starter", "Iniciador de fuego"),
        ("Reusable Water Bottle", "Cantimplora / Botella reutilizable"),
        ("Water Filter", "Filtro de agua"),
        ("Water Purification Tablets", "Tabletas purificadoras de agua"),
        ("Camping Stove", "Hornillo de gas"),
        ("Fuel Canister", "Bombona de gas"),
        ("Cooking Pot", "Olla de camping"),
        ("Frying Pan", "Sartén de camping"),
        ("Camping Utensils", "Cubiertos de camping"),
        ("Camping Plate", "Plato de camping"),
        ("Camping Mug", "Taza de camping"),
        ("Cooler", "Nevera portátil"),
        ("Ice Packs", "Bolsas de hielo"),
        ("Camping Chair", "Silla de camping"),
        ("Camping Table", "Mesa de camping"),
        ("Hammock", "Hamaca"),
        ("Tarp", "Lona impermeable"),
        ("Rope / Paracord", "Cuerda / Paracord"),
        ("Duct Tape", "Cinta americana"),
        ("Camping Saw", "Sierra de camping"),
        ("Axe / Hatchet", "Hacha / Hachuela"),
        ("Shovel", "Pala"),
        ("Bear Canister", "Contenedor para osos"),
        ("Bear Spray", "Spray para osos"),
        ("Whistle", "Silbato"),
        ("Compass", "Brújula"),
        ("Map", "Mapa"),
        ("GPS Device", "Dispositivo GPS"),
        ("Binoculars", "Prismáticos"),
        ("Field Guide", "Guía de campo"),
        ("Notebook", "Cuaderno de campo"),
        ("Camera", "Cámara"),
        ("Tripod", "Trípode"),
        ("Solar Charger", "Cargador solar"),
        ("Power Bank", "Batería externa"),
        ("Camping Repair Kit", "Kit de reparación de camping"),
        ("Duct Tape", "Cinta americana"),
        ("Zip Ties", "Bridas"),
        ("Sewing Kit", "Kit de costura"),
    ],
    ("Hiking & Trekking", "Senderismo y Trekking"): [
        ("Hiking Backpack", "Mochila de senderismo"),
        ("Daypack", "Mochila de día"),
        ("Hiking Boots", "Botas de senderismo"),
        ("Hiking Shoes", "Zapatillas de senderismo"),
        ("Hiking Socks", "Calcetines de senderismo"),
        ("Hiking Poles", "Bastones de senderismo"),
        ("Trail Map", "Mapa de sendero"),
        ("Compass", "Brújula"),
        ("GPS Device", "Dispositivo GPS"),
        ("Whistle", "Silbato"),
        ("Headlamp", "Linterna frontal"),
        ("Extra Batteries", "Pilas de repuesto"),
        ("Water Bottle", "Botella de agua"),
        ("Hydration Pack", "Sistema de hidratación"),
        ("Water Filter", "Filtro de agua"),
        ("Trail Snacks", "Snacks de sendero"),
        ("Energy Bars", "Barritas energéticas"),
        ("First Aid Kit", "Botiquín de primeros auxilios"),
        ("Emergency Blanket", "Manta de emergencia"),
        ("Fire Starter", "Iniciador de fuego"),
        ("Multi-tool", "Herramienta multiusos"),
        ("Knife", "Cuchillo"),
        ("Sunscreen", "Protector solar"),
        ("Sunglasses", "Gafas de sol"),
        ("Hat", "Sombrero"),
        ("Rain Jacket", "Chaqueta impermeable"),
        ("Rain Pants", "Pantalones impermeables"),
        ("Fleece Jacket", "Chaqueta de forro polar"),
        ("Base Layer", "Capa base"),
        ("Hiking Pants", "Pantalones de senderismo"),
        ("Hiking Shorts", "Pantalones cortos de senderismo"),
        ("Gaiters", "Polainas"),
        ("Insect Repellent", "Repelente de insectos"),
        ("Tick Remover", "Extractor de garrapatas"),
        ("Blister Kit", "Kit de ampollas"),
        ("Moleskin", "Piel de topo"),
        ("Trekking Gloves", "Guantes de trekking"),
        ("Camera", "Cámara"),
        ("Binoculars", "Prismáticos"),
        ("Field Guide", "Guía de campo"),
    ],
    ("Swimming & Water Sports", "Natación y Deportes Acuáticos"): [
        ("Swimsuit", "Bañador"),
        ("Swim Trunks", "Bañador corto"),
        ("Rash Guard", "Camiseta de protección solar"),
        ("Swim Goggles", "Gafas de natación"),
        ("Swim Cap", "Gorro de natación"),
        ("Swim Fins", "Aletas de natación"),
        ("Snorkel", "Tubo de respiración"),
        ("Snorkel Mask", "Máscara de snorkel"),
        ("Dive Mask", "Máscara de buceo"),
        ("Dive Computer", "Ordenador de buceo"),
        ("Wetsuit", "Traje de neopreno"),
        ("Dry Suit", "Traje seco"),
        ("Life Jacket", "Chaleco salvavidas"),
        ("Buoyancy Aid", "Ayuda a la flotabilidad"),
        ("Surfboard", "Tabla de surf"),
        ("Surfboard Leash", "Cuerda de tabla de surf"),
        ("Surf Wax", "Cera para tabla de surf"),
        ("Paddleboard", "Tabla de paddle surf"),
        ("Paddle", "Remo"),
        ("Kayak", "Kayak"),
        ("Canoe", "Canoa"),
        ("Water Shoes", "Zapatos de agua"),
        ("Waterproof Bag", "Bolsa impermeable"),
        ("Waterproof Phone Case", "Funda impermeable para móvil"),
        ("Underwater Camera", "Cámara submarina"),
        ("GoPro", "Cámara GoPro"),
        ("GoPro Mount", "Soporte para GoPro"),
        ("Waterproof Watch", "Reloj impermeable"),
        ("Swim Towel", "Toalla de natación"),
        ("Beach Towel", "Toalla de playa"),
        ("Sunscreen", "Protector solar"),
        ("After-Sun Lotion", "Loción post-solar"),
        ("Lip Balm with SPF", "Bálsamo labial con SPF"),
        ("Hair Ties", "Gomas de pelo"),
        ("Hair Clip", "Pinza de pelo"),
        ("Water Bottle", "Botella de agua"),
        ("Snacks", "Snacks"),
        ("Cooler", "Nevera portátil"),
        ("Beach Chair", "Silla de playa"),
        ("Beach Umbrella", "Sombrilla de playa"),
    ],
    ("Skiing & Snowboarding", "Esquí y Snowboard"): [
        ("Skis", "Esquís"),
        ("Ski Boots", "Botas de esquí"),
        ("Ski Poles", "Bastones de esquí"),
        ("Ski Bindings", "Fijaciones de esquí"),
        ("Snowboard", "Tabla de snowboard"),
        ("Snowboard Boots", "Botas de snowboard"),
        ("Snowboard Bindings", "Fijaciones de snowboard"),
        ("Helmet", "Casco"),
        ("Goggles", "Gafas de esquí"),
        ("Ski Jacket", "Chaqueta de esquí"),
        ("Ski Pants", "Pantalones de esquí"),
        ("Base Layer Top", "Capa base superior"),
        ("Base Layer Bottom", "Capa base inferior"),
        ("Mid Layer", "Capa intermedia"),
        ("Fleece Jacket", "Chaqueta de forro polar"),
        ("Ski Socks", "Calcetines de esquí"),
        ("Ski Gloves", "Guantes de esquí"),
        ("Glove Liners", "Forros de guantes"),
        ("Hand Warmers", "Calientamanos"),
        ("Toe Warmers", "Calientapiés"),
        ("Neck Gaiter", "Buff / Calentador de cuello"),
        ("Balaclava", "Pasamontañas"),
        ("Beanie", "Gorro"),
        ("Ski Backpack", "Mochila de esquí"),
        ("Avalanche Beacon", "Baliza de avalancha"),
        ("Avalanche Probe", "Sonda de avalancha"),
        ("Avalanche Shovel", "Pala de avalancha"),
        ("Ski Wax", "Cera de esquí"),
        ("Ski Tools", "Herramientas de esquí"),
        ("Ski Lock", "Candado de esquí"),
        ("Ski Bag", "Bolsa de esquí"),
        ("Snowboard Bag", "Bolsa de snowboard"),
        ("Boot Bag", "Bolsa de botas"),
        ("Goggle Case", "Funda para gafas"),
        ("Helmet Bag", "Bolsa de casco"),
        ("Sunscreen", "Protector solar"),
        ("Lip Balm with SPF", "Bálsamo labial con SPF"),
        ("Ski Pass", "Forfait"),
        ("Trail Map", "Mapa de pistas"),
    ],
    ("Professional Photography", "Fotografía profesional"): [
        ("Camera", "Cámara"),
        ("Lenses", "Objetivos"),
        ("Lens Hood", "Parasol de objetivo"),
        ("Tripod", "Trípode"),
        ("Monopod", "Monopie"),
        ("Memory Cards", "Tarjetas de memoria"),
        ("Memory Card Reader", "Lector de tarjetas de memoria"),
        ("Camera Batteries", "Baterías de cámara"),
        ("Battery Charger", "Cargador de batería"),
        ("Power Bank", "Batería externa"),
        ("Camera Cleaning Kit", "Kit de limpieza de cámara"),
        ("Air Blower", "Soplador de aire"),
        ("Sensor Cleaning Kit", "Kit de limpieza de sensor"),
        ("Camera Strap", "Correa de cámara"),
        ("Wrist Strap", "Correa de muñeca"),
        ("Camera Remote", "Disparador remoto"),
        ("Intervalometer", "Intervalómetro"),
        ("Flash", "Flash"),
        ("Flash Diffuser", "Difusor de flash"),
        ("Reflector", "Reflector"),
        ("Light Meter", "Exposímetro"),
        ("Gray Card", "Tarjeta gris"),
        ("Color Checker", "Carta de colores"),
        ("ND Filters", "Filtros ND"),
        ("Polarizing Filter", "Filtro polarizador"),
        ("UV Filter", "Filtro UV"),
        ("Graduated ND Filter", "Filtro ND degradado"),
        ("Filter Holder", "Portafiltros"),
        ("Light Stand", "Soporte de luz"),
        ("Softbox", "Softbox"),
        ("Umbrella", "Paraguas"),
        ("Backdrop", "Fondo"),
    ],
    ("Music", "Música"): [
        ("Guitar", "Guitarra"),
        ("Guitar Case", "Funda de guitarra"),
        ("Guitar Strap", "Correa de guitarra"),
        ("Guitar Picks", "Púas de guitarra"),
        ("Guitar Tuner", "Afinador de guitarra"),
        ("Guitar Strings", "Cuerdas de guitarra"),
        ("Capo", "Cejilla"),
        ("Guitar Cable", "Cable de guitarra"),
        ("Amplifier", "Amplificador"),
        ("Amp Cable", "Cable de amplificador"),
        ("Effects Pedals", "Pedales de efectos"),
        ("Pedalboard", "Pedalera"),
        ("Power Supply", "Fuente de alimentación"),
        ("Patch Cables", "Cables patch"),
        ("Drum Sticks", "Baquetas"),
        ("Drum Key", "Llave de batería"),
        ("Drum Heads", "Parches de batería"),
        ("Cymbals", "Platillos"),
        ("Cymbal Bag", "Bolsa de platillos"),
        ("Keyboard", "Teclado"),
        ("Keyboard Stand", "Soporte de teclado"),
        ("Keyboard Case", "Funda de teclado"),
        ("Sustain Pedal", "Pedal de sustain"),
        ("Keyboard Cable", "Cable de teclado"),
        ("MIDI Controller", "Controlador MIDI"),
        ("Audio Interface", "Interfaz de audio"),
        ("Microphone", "Micrófono"),
        ("Microphone Stand", "Soporte de micrófono"),
        ("Microphone Cable", "Cable de micrófono"),
        ("Pop Filter", "Filtro antipop"),
        ("Headphones", "Auriculares"),
        ("Studio Monitors", "Monitores de estudio"),
        ("Monitor Stands", "Soportes de monitores"),
        ("Recording Software", "Software de grabación"),
        ("Laptop", "Portátil"),
        ("Laptop Stand", "Soporte de portátil"),
        ("Music Stand", "Atril"),
        ("Sheet Music", "Partituras"),
        ("Metronome", "Metrónomo"),
    ],
    ("Festival & Concert", "Festival y Concierto"): [
        ("Tickets", "Entradas"),
        ("ID / Passport", "DNI / Pasaporte"),
        ("Cash", "Dinero en efectivo"),
        ("Credit Card", "Tarjeta de crédito"),
        ("Phone", "Teléfono móvil"),
        ("Phone Charger", "Cargador de móvil"),
        ("Power Bank", "Batería externa"),
        ("Earplugs", "Tapones para los oídos"),
        ("Sunglasses", "Gafas de sol"),
        ("Sunscreen", "Protector solar"),
        ("Hat / Cap", "Sombrero / Gorra"),
        ("Bandana", "Pañuelo"),
        ("Face Mask", "Mascarilla"),
        ("Rain Jacket", "Chaqueta impermeable"),
        ("Poncho", "Poncho"),
        ("Umbrella", "Paraguas"),
        ("Folding Chair", "Silla plegable"),
        ("Blanket", "Manta"),
        ("Towel", "Toalla"),
        ("Water Bottle", "Botella de agua"),
        ("Reusable Cup", "Vaso reutilizable"),
        ("Snacks", "Snacks"),
        ("Hand Sanitizer", "Desinfectante de manos"),
        ("Tissues", "Pañuelos de papel"),
        ("Wet Wipes", "Toallitas húmedas"),
        ("First Aid Kit", "Botiquín de primeros auxilios"),
        ("Painkillers", "Analgésicos"),
        ("Antihistamines", "Antihistamínicos"),
        ("Insect Repellent", "Repelente de insectos"),
        ("Flashlight", "Linterna"),
        ("Headlamp", "Linterna frontal"),
        ("Glow Sticks", "Pulseras luminosas"),
        ("LED Lights", "Luces LED"),
        ("Flag", "Bandera"),
        ("Banner", "Pancarta"),
        ("Camera", "Cámara"),
        ("GoPro", "Cámara GoPro"),
        ("Binoculars", "Prismáticos"),
        ("Fanny Pack", "Riñonera"),
    ],
    ("Road Trip", "Viaje por Carretera"): [
        ("Driver's License", "Carnet de conducir"),
        ("Car Insurance", "Seguro de coche"),
        ("Car Registration", "Permiso de circulación"),
        ("Car Keys", "Llaves del coche"),
        ("Spare Key", "Llave de repuesto"),
        ("GPS / Navigation", "GPS / Navegación"),
        ("Road Maps", "Mapas de carreteras"),
        ("Car Charger", "Cargador de coche"),
        ("Phone Mount", "Soporte para móvil"),
        ("Dash Cam", "Cámara de salpicadero"),
        ("Emergency Kit", "Kit de emergencia"),
        ("First Aid Kit", "Botiquín de primeros auxilios"),
        ("Jumper Cables", "Cables de arranque"),
        ("Tire Pressure Gauge", "Manómetro de neumáticos"),
        ("Spare Tire", "Rueda de repuesto"),
        ("Jack", "Gato"),
        ("Lug Wrench", "Llave de tuercas"),
        ("Flashlight", "Linterna"),
        ("Reflective Triangles", "Triángulos reflectantes"),
        ("Reflective Vest", "Chaleco reflectante"),
        ("Fire Extinguisher", "Extintor"),
        ("Ice Scraper", "Rascador de hielo"),
        ("Snow Chains", "Cadenas de nieve"),
        ("Blanket", "Manta"),
        ("Pillow", "Almohada"),
        ("Sleeping Bag", "Saco de dormir"),
        ("Cooler", "Nevera portátil"),
        ("Ice Packs", "Bolsas de hielo"),
        ("Snacks", "Snacks"),
        ("Water Bottle", "Botella de agua"),
        ("Travel Mug", "Taza de viaje"),
        ("Reusable Utensils", "Cubiertos reutilizables"),
        ("Paper Towels", "Papel de cocina"),
        ("Trash Bags", "Bolsas de basura"),
        ("Car Vacuum", "Aspiradora de coche"),
        ("Car Freshener", "Ambientador de coche"),
        ("Sunglasses", "Gafas de sol"),
        ("Road Trip Playlist", "Playlist de viaje por carretera"),
        ("Audiobooks", "Audiolibros"),
    ],
    ("Study Abroad", "Estudio en el Extranjero"): [
        ("Passport", "Pasaporte"),
        ("Visa", "Visado"),
        ("Student ID", "Carnet de estudiante"),
        ("University Acceptance Letter", "Carta de aceptación universitaria"),
        ("Transcripts", "Expediente académico"),
        ("Diploma", "Diploma"),
        ("Scholarship Documents", "Documentos de beca"),
        ("Health Insurance", "Seguro médico"),
        ("Vaccination Records", "Registros de vacunación"),
        ("Prescription Medication", "Medicación recetada"),
        ("Laptop", "Portátil"),
        ("Laptop Charger", "Cargador de portátil"),
        ("Laptop Bag", "Maletín para portátil"),
        ("Textbooks", "Libros de texto"),
        ("Notebooks", "Cuadernos"),
        ("Pens & Pencils", "Bolígrafos y lápices"),
        ("Highlighters", "Rotuladores fluorescentes"),
        ("Calculator", "Calculadora"),
        ("USB Drive", "Memoria USB"),
        ("External Hard Drive", "Disco duro externo"),
        ("Headphones", "Auriculares"),
        ("Phone", "Teléfono móvil"),
        ("Phone Charger", "Cargador de móvil"),
        ("Power Bank", "Batería externa"),
        ("Plug Adapter", "Adaptador de enchufe"),
        ("Backpack", "Mochila"),
        ("Day Bag", "Bolsa de día"),
        ("Water Bottle", "Botella de agua"),
        ("Reusable Coffee Cup", "Taza de café reutilizable"),
        ("Lunch Box", "Fiambrera"),
        ("Umbrella", "Paraguas"),
        ("Rain Jacket", "Chaqueta impermeable"),
        ("Winter Coat", "Abrigo de invierno"),
        ("Formal Outfit", "Conjunto formal"),
        ("Casual Clothes", "Ropa casual"),
    ],
    ("Business Travel", "Viaje de Negocios"): [
        ("Passport", "Pasaporte"),
        ("Visa", "Visado"),
        ("Business Visa", "Visado de negocios"),
        ("Company ID", "Identificación de empresa"),
        ("Business Cards", "Tarjetas de visita"),
        ("Company Letterhead", "Membrete de empresa"),
        ("Contracts", "Contratos"),
        ("Proposals", "Propuestas"),
        ("Reports", "Informes"),
        ("Presentations", "Presentaciones"),
        ("Laptop", "Portátil"),
        ("Laptop Charger", "Cargador de portátil"),
        ("Laptop Bag", "Maletín para portátil"),
        ("Mouse", "Ratón"),
        ("Mouse Pad", "Alfombrilla de ratón"),
        ("USB Drive", "Memoria USB"),
        ("External Hard Drive", "Disco duro externo"),
        ("HDMI Cable", "Cable HDMI"),
        ("Power Strip", "Regleta de enchufes"),
        ("Phone", "Teléfono móvil"),
        ("Phone Charger", "Cargador de móvil"),
        ("Power Bank", "Batería externa"),
        ("Headset", "Auriculares con micrófono"),
        ("Webcam", "Cámara web"),
        ("Formal Suit", "Traje formal"),
        ("Dress Shirts", "Camisas de vestir"),
        ("Ties", "Corbatas"),
        ("Dress Shoes", "Zapatos de vestir"),
        ("Dress Socks", "Calcetines de vestir"),
        ("Belt", "Cinturón"),
        ("Briefcase", "Maletín"),
        ("Luggage", "Equipaje"),
        ("Garment Bag", "Funda para trajes"),
        ("Toiletry Kit", "Neceser"),
        ("Business Casual Clothes", "Ropa business casual"),
        ("Casual Clothes", "Ropa casual"),
        ("Pajamas", "Pijama"),
        ("Underwear", "Ropa interior"),
    ],
}

def seed_massive_data():
    with app.app_context():
        added_categories = 0
        added_items = 0

        for (cat_en, cat_es), items in MASSIVE_SEED_DATA.items():
            category = Category.query.filter_by(name_en=cat_en, user_id=None).first()

            if not category:
                category = Category(name_en=cat_en, name_es=cat_es, user_id=None)
                db.session.add(category)
                db.session.commit()
                added_categories += 1

            for item_en, item_es in items:
                item = Item.query.filter_by(name_en=item_en, category_id=category.id, user_id=None).first()

                if not item:
                    new_item = Item(category_id=category.id, name_en=item_en, name_es=item_es, user_id=None)
                    db.session.add(new_item)
                    added_items += 1

            db.session.commit()

        print("=========================================")
        print("✅ Database successfully updated!")
        print(f"📁 Categories added: {added_categories}")
        print(f"📝 Items added: {added_items}")
        print("=========================================")

if __name__ == '__main__':
    seed_massive_data()
